/**
        Created by: Krzysztof Dobrzynski - k.dobrzynski94@gmail.com
                https://github.com/Sejoslaw
        This file is a machine generated header for JavaDotNet
        Java to .NET Open-Source Bridge.

        This file was generated with command:
        javah -classpath JavaDotNet/bin -jni -d JavaDotNet.VS/JavaDotNet.NET/JavaDotNet.NET main.java.kd.jdn.JavaDotNet

        For the current version of JavaDotNet look in: main/java/kd/jdn/JavaDotNet#version
*/

#pragma once

/// Visual Studio only include header file
#include "stdafx.h"

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_java_kd_jdn_JavaDotNet */

#ifndef _Included_main_java_kd_jdn_JavaDotNet
#define _Included_main_java_kd_jdn_JavaDotNet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_java_kd_jdn_JavaDotNet
 * Method:    communicateDotNet
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_main_java_kd_jdn_JavaDotNet_communicateDotNet
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
